services:
  api:
    build:
      context: .
      target: production
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_PATH: /app/data/arqweb.sqlite
    volumes:
      - ./data:/app/data
    restart: unless-stopped
